var dataset =  {
    'Faroe Islands' : 'fo', 
    'United States' : 'us', 
    'Japan' : 'jp', 
    'India' : 'in', 
    'France' : 'fr', 
    'China' : 'cn', 
    'Portugal' : 'pt', 
    'Serranilla Bank' : 'sw', 
    'Scarborough Reef' : 'sh', 
    'Ecuador' : 'ec', 
    'Australia' : 'au', 
    'Philippines' : 'ph', 
    'Spain' : 'es', 
    'Bajo Nuevo Bank (Petrel Is.)' : 'bu', 
    'Maldives' : 'mv', 
    'Spratly Islands' : 'sp', 
    'United Kingdom' : 'gb', 
    'Greece' : 'gr', 
    'Denmark' : 'dk', 
    'Greenland' : 'gl', 
    'Puerto Rico' : 'pr', 
    'United States Minor Outlying Islands' : 'um', 
    'United States Virgin Islands' : 'vi', 
    'Canada' : 'ca', 
    'Argentina' : 'ar', 
    'Chile' : 'cl', 
    'Cape Verde' : 'cv', 
    'Dominica' : 'dm', 
    'Seychelles' : 'sc', 
    'Jamaica' : 'jm', 
    'Oman' : 'om', 
    'Saint Vincent and the Grenadines' : 'vc', 
    'Solomon Islands' : 'sb', 
    'Saint Lucia' : 'lc', 
    'Norway' : 'no', 
    'Saint Kitts and Nevis' : 'kn', 
    'Bahrain' : 'bh', 
    'Indonesia' : 'id', 
    'Mauritius' : 'mu', 
    'Sweden' : 'se', 
    'Russia' : 'ru', 
    'Trinidad and Tobago' : 'tt', 
    'Brazil' : 'br', 
    'The Bahamas' : 'bs', 
    'Palau' : 'pw', 
    'Grenada' : 'gd', 
    'Antigua and Barbuda' : 'ag', 
    'Fiji' : 'fj', 
    'Barbados' : 'bb', 
    'Italy' : 'it', 
    'Malta' : 'mt', 
    'Papua New Guinea' : 'pg', 
    'Vanuatu' : 'vu', 
    'Singapore' : 'sg', 
    'Cyprus' : 'cy', 
    'Comoros' : 'km', 
    'Vatican' : 'va', 
    'San Marino' : 'sm', 
    'Armenia' : 'am', 
    'Azerbaijan' : 'az', 
    'Tajikistan' : 'tj', 
    'Uzbekistan' : 'uz', 
    'Lesotho' : 'ls', 
    'Bangladesh' : 'bd', 
    'North Korea' : 'kp', 
    'Kyrgyzstan' : 'kg', 
    'Mexico' : 'mx', 
    'Morocco' : 'ma', 
    'Colombia' : 'co', 
    'Tanzania' : 'tz', 
    'Saudi Arabia' : 'sa', 
    'Qatar' : 'qa', 
    'Netherlands' : 'nl', 
    'Yemen' : 'ye', 
    'United Arab Emirates' : 'ae', 
    'Kenya' : 'ke', 
    'Turkey' : 'tr', 
    'Finland' : 'fi', 
    'Malaysia' : 'my', 
    'Panama' : 'pa', 
    'Iran' : 'ir', 
    'Haiti' : 'ht', 
    'Dominican Republic' : 'do', 
    'Croatia' : 'hr', 
    'Thailand' : 'th', 
    'Estonia' : 'ee', 
    'Congo' : 'cd', 
    'Kuwait' : 'kw', 
    'Germany' : 'de', 
    'Ireland' : 'ie', 
    'Myanmar' : 'mm', 
    'Equatorial Guinea' : 'gq', 
    'Uganda' : 'ug', 
    'Kazakhstan' : 'kz', 
    'Gabon' : 'ga', 
    'South Korea' : 'kr', 
    'East Timor' : 'tl', 
    'Mauritania' : 'mr', 
    'Algeria' : 'dz', 
    'Peru' : 'pe', 
    'Angola' : 'ao', 
    'Mozambique' : 'mz', 
    'Costa Rica' : 'cr', 
    'El Salvador' : 'sv', 
    'Guatemala' : 'gt', 
    'Belize' : 'bz', 
    'Venezuela' : 've', 
    'Guyana' : 'gy', 
    'Honduras' : 'hn', 
    'Nicaragua' : 'ni', 
    'Malawi' : 'mw', 
    'Turkmenistan' : 'tm', 
    'Zambia' : 'zm', 
    'Northern Cyprus' : 'nc', 
    'South Africa' : 'za', 
    'Lithuania' : 'lt', 
    'Ethiopia' : 'et', 
    'Ghana' : 'gh', 
    'Slovenia' : 'si', 
    'Bosnia and Herzegovina' : 'ba', 
    'Jordan' : 'jo', 
    'Syria' : 'sy', 
    'Monaco' : 'mc', 
    'Albania' : 'al', 
    'Uruguay' : 'uy', 
    'Cyprus No Mans Area' : 'cn',
    'Mongolia' : 'mn', 
    'Rwanda' : 'rw', 
    'Bolivia' : 'bo', 
    'Cameroon' : 'cm', 
    'Republic of Congo' : 'cg', 
    'Western Sahara' : 'eh', 
    'Republic of Serbia' : 'rs', 
    'Montenegro' : 'me', 
    'Benin' : 'bj', 
    'Nigeria' : 'ng', 
    'Togo' : 'tg', 
    'Laos' : 'la', 
    'Afghanistan' : 'af', 
    'Ukraine' : 'ua', 
    'Slovakia' : 'sk', 
    'Siachen Glacier' : 'jk', 
    'Pakistan' : 'pk', 
    'Bulgaria' : 'bg', 
    'Liechtenstein' : 'li', 
    'Austria' : 'at', 
    'Swaziland' : 'sz', 
    'Hungary' : 'hu', 
    'Niger' : 'ne', 
    'Luxembourg' : 'lu', 
    'Andorra' : 'ad', 
    'Ivory Coast' : 'ci', 
    'Liberia' : 'lr', 
    'Sierra Leone' : 'sl', 
    'Brunei' : 'bn', 
    'Belgium' : 'be', 
    'Iraq' : 'iq', 
    'Georgia' : 'ge', 
    'Gambia' : 'gm', 
    'Switzerland' : 'ch', 
    'Chad' : 'td', 
    'Kosovo' : 'kv', 
    'Lebanon' : 'lb', 
    'Somaliland' : 'sx', 
    'Djibouti' : 'dj', 
    'Eritrea' : 'er', 
    'Burundi' : 'bi', 
    'Suriname' : 'sr', 
    'Israel' : 'il', 
    'Guinea Bissau' : 'gw', 
    'Senegal' : 'sn', 
    'Guinea' : 'gn', 
    'Poland' : 'pl', 
    'Macedonia' : 'mk', 
    'Paraguay' : 'py', 
    'Belarus' : 'by', 
    'Latvia' : 'lv', 
    'Burkina Faso' : 'bf', 
    'Namibia' : 'na', 
    'Romania' : 'ro', 
    'Zimbabwe' : 'zw', 
    'Cambodia' : 'kh', 
    'Sudan' : 'sd', 
    'Czech Republic' : 'cz', 
    'Mali' : 'ml', 
    'Bhutan' : 'bt', 
    'Botswana' : 'bw', 
    'Moldova' : 'md', 
    'Central African Republic' : 'cf', 
    'New Zealand' : 'nz', 
    'Cuba' : 'cu', 
    'Vietnam' : 'vn', 
    'Tunisia' : 'tn', 
    'Taiwan' : 'tw', 
    'Madagascar' : 'mg', 
    'Iceland' : 'is', 
    'Sri Lanka' : 'lk', 
    'Somalia' : 'so', 
    'Egypt' : 'eg', 
    'Libya' : 'ly', 
    'Nepal' : 'np'
    
};

function getCountry(hckey) {
    if (dataset.hasOwnProperty(hckey)) {
        return dataset[hckey];
    } else {
        return hckey;
    }
};
